### ISSUE TITLE
Wrong Cell current when Np>1?

### ISSUE THREAD

**Issue by max-privato** [raulrpearson/PVSystems#7]
Consider Electrical,PVArray model. 
In the active region it is:
`i = -Np*(Ipv - Id - Ir);`
I think that Ipv and Id are cell currents, and therefore for computing the array current they must be multiplied by Np. the definition of Ir, instead is:
  Ir = (v - Rs*i)/Rp;
therefore it is already the "array" current flowing through Rp. Therefore I think the formula for i should be changed into:
`i = -Np*(Ipv - Id) + Ir;`

**Comment by raulrpearson** [comment]
Thanks for your comment @max-privato. Are you still interested in figuring this out?

It's a long time since I completed this project and I don't have the right context loaded into my brain, so I might be missing something. Check out chapter 3 of the [thesis doc](http://www.euclides.dia.uned.es/aurquia/Files/TFM_Raul_Rodriguez_Pearson.pdf) and let me know what you think.

By applying Kirchoff we have that `i = Ipv - Id - Ir` for one cell. Times `Np` for parallel cells. Also check out  "Comprehensive Approach to Modeling and Simulation of Photovoltaic Arrays" by M.G. Villalva et al.

Let me know if that helps.

**Comment by max-privato** [comment]
> Thanks for your comment @max-privato. Are you still interested in figuring this out?

Personally, I don't need this ticket to be solved anymore.
For the time being, I don't simulate PV systems; moreover, during the last two years, I felt comfortable with Photovoltaics.
Thank you for your consideration of my report.
